// Catalog data for Wellcare Mart
export type Product = {
  id: string;
  name: string;
  brand: string;
  cat: string;
  category_name?: string;
  price: number;
  was?: number;
  rating: number;
  reviews: number;
  stock: string;
  tags: string[];
  blurb: string;
  swatch: string;
  image_url?: string | null;
};

export const CATEGORIES = [
  { id: "all", name: "All products", count: 0 },
  { id: "glucometers", name: "Glucometers", count: 0 },
  { id: "bp-digital", name: "BP Digital", count: 0 },
  { id: "bp-manual", name: "BP Manual", count: 0 },
  { id: "weight-scale-digital", name: "Weight Scale Digital", count: 0 },
  { id: "weight-scale-manual", name: "Weight Scale Manual", count: 0 },
  { id: "camote-chairs", name: "Imported Camote Chairs", count: 0 },
  { id: "walkers", name: "Imported Walkers", count: 0 },
  { id: "patient-sticks", name: "Patient Sticks", count: 0 },
  { id: "wheelchairs", name: "Wheel Chairs", count: 0 },
  { id: "sugar-strips", name: "Sugar Strips", count: 0 },
  { id: "hearing-aids", name: "Hearing Aids", count: 0 },
  { id: "heating-pad", name: "Heating Pad", count: 0 },
  { id: "air-mattress", name: "Air Mattress", count: 0 },
  { id: "tens-machine", name: "Tens Machine", count: 0 },
  { id: "nebulizer", name: "Nebulizer", count: 0 },
  { id: "stethoscope", name: "Stethoscope", count: 0 },
  { id: "massagers", name: "Massagers", count: 0 },
  { id: "ortho-belts", name: "Ortho Belts", count: 0 },
  { id: "supports", name: "Supports", count: 0 },
  { id: "breast-pump", name: "Breast Pump", count: 0 },
  { id: "steamers", name: "Steamers", count: 0 },
  { id: "suction-machine", name: "Suction Machine", count: 0 },
  { id: "other", name: "Other Items", count: 0 },
];

export const PKR = (n: number) => "Rs " + n.toLocaleString("en-PK");

export const PRODUCTS: Product[] = [
  // Glucometers
  {
    id: "gluco-001",
    name: "Accu Check Active",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-002",
    name: "Accu Check Instant",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-003",
    name: "Accu Check Instant S",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-004",
    name: "Evo Check Go",
    brand: "",
    cat: "glucometers",
    price: 1700,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-005",
    name: "On Call",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-006",
    name: "On Call Extra",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-007",
    name: "Atom",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-008",
    name: "Master",
    brand: "",
    cat: "glucometers",
    price: 700,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-009",
    name: "Medisign",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-010",
    name: "Evo Check",
    brand: "",
    cat: "glucometers",
    price: 3400,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "gluco-011",
    name: "Life Check",
    brand: "",
    cat: "glucometers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  // BP Digital
  {
    id: "bp-dig-001",
    name: "Omron M1",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-002",
    name: "Medisign 804",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-003",
    name: "Medisign 830",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-004",
    name: "Medisign BPM 36",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-005",
    name: "Medicare 631A",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-006",
    name: "Medicare 814",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-007",
    name: "Atom 704",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-008",
    name: "Ucheck 8008",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-009",
    name: "Certeza BP 450",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-010",
    name: "ABM BP Monitor",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-dig-011",
    name: "Life Check 6250",
    brand: "",
    cat: "bp-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  // BP Manual
  {
    id: "bp-man-001",
    name: "Yuwell",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-002",
    name: "Atom",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-003",
    name: "Medisign",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-004",
    name: "Certeza",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-005",
    name: "ABM",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-006",
    name: "Senior",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-007",
    name: "Master",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "bp-man-008",
    name: "Certeza Aneroid Blue",
    brand: "",
    cat: "bp-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  // Weight Scale Digital
  {
    id: "wsd-001",
    name: "Camry",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-002",
    name: "Life Care",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-003",
    name: "Kitchen Scale",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-004",
    name: "Evo Check",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-005",
    name: "Certeza",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-006",
    name: "Blevia",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-007",
    name: "Baby Weight Scale",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsd-008",
    name: "Senior",
    brand: "",
    cat: "weight-scale-digital",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  // Weight Scale Manual
  {
    id: "wsm-001",
    name: "Camry",
    brand: "",
    cat: "weight-scale-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsm-002",
    name: "Life Care",
    brand: "",
    cat: "weight-scale-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsm-003",
    name: "Evo Check",
    brand: "",
    cat: "weight-scale-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsm-004",
    name: "Certeza",
    brand: "",
    cat: "weight-scale-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsm-005",
    name: "Blevia",
    brand: "",
    cat: "weight-scale-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wsm-006",
    name: "Senior",
    brand: "",
    cat: "weight-scale-manual",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  // Imported Camote Chairs
  {
    id: "cc-001",
    name: "Secure Camote Chair",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-002",
    name: "Life Care Camote Chair",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-003",
    name: "Secure Camote Chair Wheel",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-004",
    name: "Life Care Camote Chair Wheel",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-005",
    name: "Secure Shower Chair",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-006",
    name: "Life Care Shower Chair",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-007",
    name: "Secure Shower Chair Wheel",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-008",
    name: "Life Care Shower Chair Wheel",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-009",
    name: "Secure Camote Raiser",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "cc-010",
    name: "Life Care Camote Raiser",
    brand: "",
    cat: "camote-chairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  // Imported Walkers
  {
    id: "wlk-001",
    name: "Secure Walker Plain",
    brand: "",
    cat: "walkers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "wlk-002",
    name: "Life Care Walker Plain",
    brand: "",
    cat: "walkers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "wlk-003",
    name: "Secure Walker Wheel",
    brand: "",
    cat: "walkers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "wlk-004",
    name: "Life Care Walker Wheel",
    brand: "",
    cat: "walkers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "wlk-005",
    name: "Rollator",
    brand: "",
    cat: "walkers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  // Patient Sticks
  {
    id: "stick-001",
    name: "Tripod Stick",
    brand: "",
    cat: "patient-sticks",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "stick-002",
    name: "Elbow Stick",
    brand: "",
    cat: "patient-sticks",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "stick-003",
    name: "Trusty Cane Stick Foldable",
    brand: "",
    cat: "patient-sticks",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "stick-004",
    name: "Besaki",
    brand: "",
    cat: "patient-sticks",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  // Wheel Chairs
  {
    id: "wc-001",
    name: "Wheel Chair 809 (Secure & Life Care)",
    brand: "",
    cat: "wheelchairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wc-002",
    name: "Wheel Chair BMW (Secure & Life Care)",
    brand: "",
    cat: "wheelchairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wc-003",
    name: "Wheel Chair 868 (Secure & Life Care)",
    brand: "",
    cat: "wheelchairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wc-004",
    name: "Wheel Chair Aclined (Secure & Life Care)",
    brand: "",
    cat: "wheelchairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "wc-005",
    name: "Electric Wheel Chair (Secure & Life Care)",
    brand: "",
    cat: "wheelchairs",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  // Sugar Strips
  {
    id: "strip-001",
    name: "Atom",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-002",
    name: "Accu Check Active",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-003",
    name: "Accu Check Instant",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-004",
    name: "Free Style",
    brand: "",
    cat: "sugar-strips",
    price: 2100,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-005",
    name: "Ucheck",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-006",
    name: "Master",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-007",
    name: "Evo Check Go",
    brand: "",
    cat: "sugar-strips",
    price: 1800,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-008",
    name: "Medisign",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-009",
    name: "Accu Check Performa",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "strip-010",
    name: "Oncall",
    brand: "",
    cat: "sugar-strips",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  // Hearing Aids
  {
    id: "hear-001",
    name: "Axon V 163",
    brand: "",
    cat: "hearing-aids",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "hear-002",
    name: "Axon K 86",
    brand: "",
    cat: "hearing-aids",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  // Heating Pad
  {
    id: "heat-001",
    name: "Atom",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "heat-002",
    name: "Ucheck",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "heat-003",
    name: "Medicare",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "heat-004",
    name: "ABM",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "heat-005",
    name: "Certeza",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "heat-006",
    name: "Accu Max",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "heat-007",
    name: "Life Care",
    brand: "",
    cat: "heating-pad",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  // Air Mattress
  {
    id: "am-001",
    name: "Atom",
    brand: "",
    cat: "air-mattress",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "am-002",
    name: "Ucheck",
    brand: "",
    cat: "air-mattress",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "am-003",
    name: "Medicare",
    brand: "",
    cat: "air-mattress",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "am-004",
    name: "Certeza",
    brand: "",
    cat: "air-mattress",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "am-005",
    name: "Accu Max",
    brand: "",
    cat: "air-mattress",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "am-006",
    name: "Life Care",
    brand: "",
    cat: "air-mattress",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  // Tens Machine
  {
    id: "tens-001",
    name: "Blue Idea Tens 610",
    brand: "",
    cat: "tens-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "tens-002",
    name: "Electronic Plus Tens",
    brand: "",
    cat: "tens-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "tens-003",
    name: "Basemed Tens 660",
    brand: "",
    cat: "tens-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "tens-004",
    name: "Senior Tens 92660",
    brand: "",
    cat: "tens-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "tens-005",
    name: "Blue Idea Tens 2008b",
    brand: "",
    cat: "tens-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  {
    id: "tens-006",
    name: "Life Care Combo Stim EMS",
    brand: "",
    cat: "tens-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "emerald",
  },
  // Nebulizer
  {
    id: "neb-001",
    name: "Ucheck",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-002",
    name: "Life Care",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-003",
    name: "Medicare",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-004",
    name: "Medicare Plus",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-005",
    name: "Active",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-006",
    name: "Apple Neb",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-007",
    name: "Strong Neb",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-008",
    name: "Micelflux",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-009",
    name: "Baby Neb",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-010",
    name: "Mesh Portable Nebulizer",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "neb-011",
    name: "Atom",
    brand: "",
    cat: "nebulizer",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  // Stethoscope
  {
    id: "steth-001",
    name: "Littmann Classic",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-002",
    name: "Certeza",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-003",
    name: "Atom",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-004",
    name: "Ucheck",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-005",
    name: "Senior",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-006",
    name: "Medico",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-007",
    name: "Life Care",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-008",
    name: "Medicare",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-009",
    name: "Blevia",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-010",
    name: "Yuwell",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "steth-011",
    name: "Medi Plus",
    brand: "",
    cat: "stethoscope",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  // Massagers
  {
    id: "mass-001",
    name: "Gun Massager",
    brand: "",
    cat: "massagers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "mass-002",
    name: "Magic Massager",
    brand: "",
    cat: "massagers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "mass-003",
    name: "Tikon Massager",
    brand: "",
    cat: "massagers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "mass-004",
    name: "Heated Massager",
    brand: "",
    cat: "massagers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  {
    id: "mass-005",
    name: "Double Head Massager",
    brand: "",
    cat: "massagers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "amber",
  },
  // Ortho Belts
  {
    id: "belt-001",
    name: "Sacro Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-002",
    name: "Sacral Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-003",
    name: "Abdominal Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-004",
    name: "Polysling",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-005",
    name: "Soft & Hard Coolers",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-006",
    name: "Pregnancy Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-007",
    name: "Shoulder Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-008",
    name: "Tummy Trimmer Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-009",
    name: "Snorkling",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "belt-010",
    name: "Posture Belt",
    brand: "",
    cat: "ortho-belts",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  // Supports
  {
    id: "supp-001",
    name: "Knee Support",
    brand: "",
    cat: "supports",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "supp-002",
    name: "Knee Gel Support",
    brand: "",
    cat: "supports",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "supp-003",
    name: "Imported Knee Support",
    brand: "",
    cat: "supports",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "supp-004",
    name: "Ankle Support",
    brand: "",
    cat: "supports",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "supp-005",
    name: "Wrist Brace",
    brand: "",
    cat: "supports",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  // Breast Pump
  {
    id: "bpump-001",
    name: "Life Care Breast Pump",
    brand: "",
    cat: "breast-pump",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "bpump-002",
    name: "Medicare Breast Pump",
    brand: "",
    cat: "breast-pump",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  {
    id: "bpump-003",
    name: "Chaina Breast Pump",
    brand: "",
    cat: "breast-pump",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "rose",
  },
  // Steamers
  {
    id: "steam-001",
    name: "Karliz Steamer",
    brand: "",
    cat: "steamers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "steam-002",
    name: "SC Steamer",
    brand: "",
    cat: "steamers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "steam-003",
    name: "Jaf Steamer",
    brand: "",
    cat: "steamers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "steam-004",
    name: "3 in 1 Steamer",
    brand: "",
    cat: "steamers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "steam-005",
    name: "4 in 1 Steamer",
    brand: "",
    cat: "steamers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  {
    id: "steam-006",
    name: "Life Care Steamer",
    brand: "",
    cat: "steamers",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "sky",
  },
  // Suction Machine
  {
    id: "suct-001",
    name: "Yuwell",
    brand: "",
    cat: "suction-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "suct-002",
    name: "Life Care",
    brand: "",
    cat: "suction-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "suct-003",
    name: "Blevia",
    brand: "",
    cat: "suction-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "suct-004",
    name: "Easy Care",
    brand: "",
    cat: "suction-machine",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  // Other Items
  {
    id: "oth-001",
    name: "Gym Balls",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-002",
    name: "Hot & Cold Gel",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-003",
    name: "Hot Water Bottle",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-004",
    name: "Thermometer Manual Digital",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-005",
    name: "Infrared Thermometer",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-006",
    name: "Adult Diapers",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-007",
    name: "Gloves",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-008",
    name: "Norvus Slime",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-009",
    name: "Drip Set",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-010",
    name: "Canula",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-011",
    name: "BP Cuffs",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-012",
    name: "Bandages",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-013",
    name: "Torch",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-014",
    name: "Food Table",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-015",
    name: "First Aid Box",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-016",
    name: "Masks",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-017",
    name: "Insole Ped",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-018",
    name: "Pulse Oximeter",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-019",
    name: "Drip Stand",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-020",
    name: "Urine Bag",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
  {
    id: "oth-021",
    name: "Urine Bottles",
    brand: "",
    cat: "other",
    price: 0,
    rating: 0,
    reviews: 0,
    stock: "In stock",
    tags: [],
    blurb: "",
    swatch: "slate",
  },
];

CATEGORIES.forEach((c) => {
  c.count = c.id === "all" ? PRODUCTS.length : PRODUCTS.filter((p) => p.cat === c.id).length;
});

export type OrderItem = { id: string; qty: number };
export type Order = {
  id: string;
  placed: string;
  eta: string;
  status: string;
  progress: number;
  address: string;
  payment: string;
  items: OrderItem[];
  subtotal: number;
  shipping: number;
  total: number;
  rider?: { name: string; phone: string };
};
